### ISSUE TITLE
Missing implementation of useScroll hook

### ISSUE THREAD

**Issue by icewind** [palmerhq/the-platform#26]
Hello. First of all, thanks for this great module! It made playing with hooks even more enjoyable. 
Maybe I missed something but I don't see an implementation of `useScroll` hook.
Is it still in TODO list?
Thanks.

**Comment by nathanforce** [comment]
Hey!

Check out `useWindowScrollPosition` and let me know if it is what you have in mind.

https://github.com/palmerhq/the-platform/blob/master/src/useWindowScrollPosition.js

Thanks!

**Comment by icewind** [comment]
Exactly! Thank you. Looks like it was a documentation issue. Or I just missed it. 
Anyway, thank you for a great job!
