### ISSUE TITLE
State var name conflicts?

### ISSUE THREAD

**Issue by AjaxSolutions** [palmerhq/the-platform#30]
This is a question.  You introduce common state var names such as _motion_ or _orientation_.

What's going to happen if I use this code and it conflicts with my own state vars w/ the same name?

Is this an issue?  Should state var names be more unique?

**Comment by nathanforce** [comment]
Hey!

This should not be an issue as the variable names are up to you.

```
  const motion = useDeviceMotion();
  const something = useDeviceMotion();
```
