### ISSUE TITLE
Support srcSet for Img

### ISSUE THREAD

**Issue by dashed** [palmerhq/the-platform#42]
Be nice to suspend on `srcSet`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset

e.g.

```
<Img src={pathToPNG} srcSet={`${pathToPNG_2x} 2x`} />
```

**Comment by jaredpalmer** [comment]
Feel free to submit a PR!

**Comment by dashed** [comment]
@jaredpalmer would this work? https://github.com/palmerhq/the-platform/pull/47
